//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectUpdated
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentTeacherItem = new HashSet<StudentTeacherItem>();
        }
    
        public int student_code { get; set; }
        public string surname { get; set; }
        public string nameStudent { get; set; }
        public string middlename { get; set; }
        public int class_code { get; set; }
        public string student_password { get; set; }
        public string student_login { get; set; }
        public byte[] studentImage { get; set; }
        public string keyword { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTeacherItem> StudentTeacherItem { get; set; }
    }
}
