//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectUpdated
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTeacherItem
    {
        public int teacher_code { get; set; }
        public int student_code { get; set; }
        public int item_code { get; set; }
        public string mark { get; set; }
        public Nullable<System.DateTime> dateMark { get; set; }
        public byte MarkID { get; set; }
        public string description { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
