//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectUpdated
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherClass
    {
        public int teacher_code { get; set; }
        public int class_code { get; set; }
        public int teacherclass_code { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
